# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Personal/FPGA/XilinxFPGA/Freq_Gen/Freq_Gen/Freq_Gen.srcs/sources_1/bd/Main_BD/ip/Main_BD_axi_uartlite_0_0/Main_BD_axi_uartlite_0_0.xci
# IP: The module: 'Main_BD_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Personal/FPGA/XilinxFPGA/Freq_Gen/Freq_Gen/Freq_Gen.gen/sources_1/bd/Main_BD/ip/Main_BD_axi_uartlite_0_0/Main_BD_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_BD_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/Freq_Gen/Freq_Gen/Freq_Gen.gen/sources_1/bd/Main_BD/ip/Main_BD_axi_uartlite_0_0/Main_BD_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_BD_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/Freq_Gen/Freq_Gen/Freq_Gen.gen/sources_1/bd/Main_BD/ip/Main_BD_axi_uartlite_0_0/Main_BD_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_BD_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Personal/FPGA/XilinxFPGA/Freq_Gen/Freq_Gen/Freq_Gen.srcs/sources_1/bd/Main_BD/ip/Main_BD_axi_uartlite_0_0/Main_BD_axi_uartlite_0_0.xci
# IP: The module: 'Main_BD_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Personal/FPGA/XilinxFPGA/Freq_Gen/Freq_Gen/Freq_Gen.gen/sources_1/bd/Main_BD/ip/Main_BD_axi_uartlite_0_0/Main_BD_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_BD_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/Freq_Gen/Freq_Gen/Freq_Gen.gen/sources_1/bd/Main_BD/ip/Main_BD_axi_uartlite_0_0/Main_BD_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_BD_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/Freq_Gen/Freq_Gen/Freq_Gen.gen/sources_1/bd/Main_BD/ip/Main_BD_axi_uartlite_0_0/Main_BD_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_BD_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
