# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Personal/FPGA/XilinxFPGA/Test_Microblaze/KCU116_Microblaze_Test.xdc

# Block Designs: bd/mainBD/mainBD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD || ORIG_REF_NAME==mainBD} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_AXI4_Lite_ER_0_0/mainBD_AXI4_Lite_ER_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_AXI4_Lite_ER_0_0 || ORIG_REF_NAME==mainBD_AXI4_Lite_ER_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_microblaze_0_0/mainBD_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_microblaze_0_0 || ORIG_REF_NAME==mainBD_microblaze_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_axi_uart16550_0_0/mainBD_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_axi_uart16550_0_0 || ORIG_REF_NAME==mainBD_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_axi_gpio_0_0/mainBD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_axi_gpio_0_0 || ORIG_REF_NAME==mainBD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_xlslice_0_0/mainBD_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_xlslice_0_0 || ORIG_REF_NAME==mainBD_xlslice_0_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_xlslice_0_1/mainBD_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_xlslice_0_1 || ORIG_REF_NAME==mainBD_xlslice_0_1} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_xlslice_1_0/mainBD_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_xlslice_1_0 || ORIG_REF_NAME==mainBD_xlslice_1_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_xlslice_2_0/mainBD_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_xlslice_2_0 || ORIG_REF_NAME==mainBD_xlslice_2_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_dlmb_v10_0/mainBD_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_dlmb_v10_0 || ORIG_REF_NAME==mainBD_dlmb_v10_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_ilmb_v10_0/mainBD_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_ilmb_v10_0 || ORIG_REF_NAME==mainBD_ilmb_v10_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_dlmb_bram_if_cntlr_0/mainBD_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mainBD_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_ilmb_bram_if_cntlr_0/mainBD_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mainBD_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_lmb_bram_0/mainBD_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_lmb_bram_0 || ORIG_REF_NAME==mainBD_lmb_bram_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_mdm_1_0/mainBD_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_mdm_1_0 || ORIG_REF_NAME==mainBD_mdm_1_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_clk_wiz_1_0/mainBD_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_clk_wiz_1_0 || ORIG_REF_NAME==mainBD_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_rst_clk_wiz_1_100M_0/mainBD_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mainBD_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_xbar_0/mainBD_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_xbar_0 || ORIG_REF_NAME==mainBD_xbar_0} -quiet] -quiet

# IP: bd/mainBD/ip/mainBD_microblaze_0_axi_periph_0/mainBD_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mainBD_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mainBD_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/Test_Microblaze/Test_Microblaze/Test_Microblaze.gen/sources_1/bd/mainBD/mainBD_ooc.xdc
