# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Personal/FPGA/XilinxFPGA/Freq_Gen/KCU116_Rev1.0_XDC_04062017.xdc

# Block Designs: bd/Main_BD/Main_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD || ORIG_REF_NAME==Main_BD} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_microblaze_0_0/Main_BD_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_microblaze_0_0 || ORIG_REF_NAME==Main_BD_microblaze_0_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_axi_uartlite_0_0/Main_BD_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_axi_uartlite_0_0 || ORIG_REF_NAME==Main_BD_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_axi_gpio_0_0/Main_BD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_axi_gpio_0_0 || ORIG_REF_NAME==Main_BD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_dlmb_v10_0/Main_BD_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_dlmb_v10_0 || ORIG_REF_NAME==Main_BD_dlmb_v10_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_ilmb_v10_0/Main_BD_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_ilmb_v10_0 || ORIG_REF_NAME==Main_BD_ilmb_v10_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_dlmb_bram_if_cntlr_0/Main_BD_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Main_BD_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_ilmb_bram_if_cntlr_0/Main_BD_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Main_BD_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_lmb_bram_0/Main_BD_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_lmb_bram_0 || ORIG_REF_NAME==Main_BD_lmb_bram_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_mdm_1_0/Main_BD_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_mdm_1_0 || ORIG_REF_NAME==Main_BD_mdm_1_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_clk_wiz_1_0/Main_BD_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_clk_wiz_1_0 || ORIG_REF_NAME==Main_BD_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_rst_clk_wiz_1_100M_0/Main_BD_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Main_BD_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_xbar_0/Main_BD_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_xbar_0 || ORIG_REF_NAME==Main_BD_xbar_0} -quiet] -quiet

# IP: bd/Main_BD/ip/Main_BD_microblaze_0_axi_periph_0/Main_BD_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_BD_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Main_BD_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/Freq_Gen/Freq_Gen/Freq_Gen.gen/sources_1/bd/Main_BD/Main_BD_ooc.xdc
