# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Personal/FPGA/XilinxFPGA/KCU116_Test/KCU116_Test/KCU116_Test.srcs/sources_1/bd/MainBD/ip/MainBD_rst_clk_wiz_1_100M_0/MainBD_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'MainBD_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Personal/FPGA/XilinxFPGA/KCU116_Test/KCU116_Test/KCU116_Test.gen/sources_1/bd/MainBD/ip/MainBD_rst_clk_wiz_1_100M_0/MainBD_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainBD_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/KCU116_Test/KCU116_Test/KCU116_Test.gen/sources_1/bd/MainBD/ip/MainBD_rst_clk_wiz_1_100M_0/MainBD_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainBD_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/KCU116_Test/KCU116_Test/KCU116_Test.gen/sources_1/bd/MainBD/ip/MainBD_rst_clk_wiz_1_100M_0/MainBD_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainBD_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Personal/FPGA/XilinxFPGA/KCU116_Test/KCU116_Test/KCU116_Test.srcs/sources_1/bd/MainBD/ip/MainBD_rst_clk_wiz_1_100M_0/MainBD_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'MainBD_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Personal/FPGA/XilinxFPGA/KCU116_Test/KCU116_Test/KCU116_Test.gen/sources_1/bd/MainBD/ip/MainBD_rst_clk_wiz_1_100M_0/MainBD_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainBD_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/KCU116_Test/KCU116_Test/KCU116_Test.gen/sources_1/bd/MainBD/ip/MainBD_rst_clk_wiz_1_100M_0/MainBD_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainBD_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/KCU116_Test/KCU116_Test/KCU116_Test.gen/sources_1/bd/MainBD/ip/MainBD_rst_clk_wiz_1_100M_0/MainBD_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MainBD_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
