# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Personal/FPGA/XilinxFPGA/Test_Microblaze/Test_Microblaze/Test_Microblaze.srcs/sources_1/bd/mainBD/ip/mainBD_dlmb_v10_0/mainBD_dlmb_v10_0.xci
# IP: The module: 'mainBD_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Personal/FPGA/XilinxFPGA/Test_Microblaze/Test_Microblaze/Test_Microblaze.gen/sources_1/bd/mainBD/ip/mainBD_dlmb_v10_0/mainBD_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mainBD_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Personal/FPGA/XilinxFPGA/Test_Microblaze/Test_Microblaze/Test_Microblaze.srcs/sources_1/bd/mainBD/ip/mainBD_dlmb_v10_0/mainBD_dlmb_v10_0.xci
# IP: The module: 'mainBD_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Personal/FPGA/XilinxFPGA/Test_Microblaze/Test_Microblaze/Test_Microblaze.gen/sources_1/bd/mainBD/ip/mainBD_dlmb_v10_0/mainBD_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mainBD_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
