# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Personal/FPGA/XilinxFPGA/KCU116_Test/KCU116_Test.xdc

# Block Designs: bd/MainBD/MainBD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD || ORIG_REF_NAME==MainBD} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_microblaze_0_0/MainBD_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_microblaze_0_0 || ORIG_REF_NAME==MainBD_microblaze_0_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_axi_uart16550_0_0/MainBD_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_axi_uart16550_0_0 || ORIG_REF_NAME==MainBD_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_dlmb_v10_0/MainBD_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_dlmb_v10_0 || ORIG_REF_NAME==MainBD_dlmb_v10_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_ilmb_v10_0/MainBD_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_ilmb_v10_0 || ORIG_REF_NAME==MainBD_ilmb_v10_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_dlmb_bram_if_cntlr_0/MainBD_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MainBD_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_ilmb_bram_if_cntlr_0/MainBD_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MainBD_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_lmb_bram_0/MainBD_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_lmb_bram_0 || ORIG_REF_NAME==MainBD_lmb_bram_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_mdm_1_0/MainBD_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_mdm_1_0 || ORIG_REF_NAME==MainBD_mdm_1_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_clk_wiz_1_0/MainBD_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_clk_wiz_1_0 || ORIG_REF_NAME==MainBD_clk_wiz_1_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_rst_clk_wiz_1_100M_0/MainBD_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MainBD_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_xbar_0/MainBD_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_xbar_0 || ORIG_REF_NAME==MainBD_xbar_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_microblaze_0_axi_periph_0/MainBD_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MainBD_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MainBD/ip/MainBD_axi_gpio_0_0/MainBD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MainBD_axi_gpio_0_0 || ORIG_REF_NAME==MainBD_axi_gpio_0_0} -quiet] -quiet

# XDC: d:/Personal/FPGA/XilinxFPGA/KCU116_Test/KCU116_Test/KCU116_Test.gen/sources_1/bd/MainBD/MainBD_ooc.xdc
